name: ganimator
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - async-timeout=4.0.1
  - attrs=21.2.0
  - blas=1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.26
  - cachetools=4.2.2
  - certifi=2021.10.8
  - cffi=1.14.6
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cryptography=3.4.8
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.18
  - expat=2.4.1
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.1
  - grpcio=1.42.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.8.2
  - intel-openmp=2021.4.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.2.0
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - oauthlib=3.1.1
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1m
  - packaging=21.3
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.2.4
  - protobuf=3.19.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - qt=5.9.7
  - readline=8.1.2
  - requests=2.27.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.7.3
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.37.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.6.0
  - tk=8.6.11
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - tornado=6.1
  - tqdm=4.62.3
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - urllib3=1.26.7
  - werkzeug=2.0.2
  - wheel=0.37.1
  - xz=5.2.5
  - yarl=1.6.3
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9